name: r2-dump

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install radare2
        run: sudo apt-get install -y radare2

      - name: Run full analysis
        run: |
          CMD="aaa;aaaa;iI;ii;afl;aflj;izz;iS;is;agfj;agfd;agfv;pdf @@ fcn.*;axt @@ /ad xor;axt @@ /ad eor"
          r2 -AA -e bin.cache=true -e anal.cc=0 -q app.so -c "$CMD" > dump.txt

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: r2-dump
          path: dump.txt
